# yamllint disable-line rule:document-start
version: 2

updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
      time: "09:00"
      timezone: Europe/London
    cooldown:
      default-days: 21
    directory: "/"
    open-pull-requests-limit: 10
